oidc_provider/urls.py
from django.urls import re_path
from django.views.decorators.csrf import csrf_exempt

from oidc_provider import (
    settings,
    views,
)

app_name = "oidc_provider"
urlpatterns = [
    re_path(r"^authorize/?$", views.AuthorizeView.as_view(), name="authorize"),
    re_path(r"^token/?$", csrf_exempt(views.TokenView.as_view()), name="token"),
    re_path(r"^userinfo/?$", csrf_exempt(views.userinfo), name="userinfo"),
    re_path(r"^end-session/?$", views.EndSessionView.as_view(), name="end-session"),
    re_path(
        r"^end-session-prompt/?$", views.EndSessionPromptView.as_view(), name="end-session-prompt"
    ),
    re_path(
        r"^\.well-known/openid-configuration/?$",
        views.ProviderInfoView.as_view(),
        name="provider-info",
    ),
    re_path(r"^introspect/?$", views.TokenIntrospectionView.as_view(), name="token-introspection"),
    re_path(r"^jwks/?$", views.JwksView.as_view(), name="jwks"),
]

if settings.get("OIDC_SESSION_MANAGEMENT_ENABLE"):
    urlpatterns += [
        re_path(
            r"^check-session-iframe/?$",
            views.CheckSessionIframeView.as_view(),
            name="check-session-iframe",
        ),
    ]

oidc_provider/templates/oidc_provider/authorize.html
{% extends 'base.html' %}
{% block content %}
<h1>Request for Permission</h1>

<p>Client <strong>{{ client.name }}</strong> would like to access this information of you ...</p>

<form method="post" action="{% url 'oidc_provider:authorize' %}">

    {% csrf_token %}

    {{ hidden_inputs }}

    <ul>
        {% for scope in scopes %}
        <li><strong>{{ scope.name }}</strong> <br><i>{{ scope.description }}</i></li>
        {% endfor %}
    </ul>

    <input type="submit" value="Decline" />
    <input name="allow" type="submit" value="Authorize" />

</form>
{% endblock %}

oidc_provider/templates/oidc_provider/check_session_iframe.html
{% load static %}

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>OP Iframe</title>
        <script src="{% static 'oidc_provider/js/sha256.min.js' %}"></script>
        <script language="JavaScript" type="text/javascript">
            window.addEventListener("message", receiveMessage, false);

            function receiveMessage(e) {
                if (!e.data || typeof e.data != 'string' || e.data == 'error') {
                    return;
                }

                var status;
                try {
                    var clientId = e.data.split(' ')[0];
                    var sessionState = e.data.split(' ')[1];
                    var salt = sessionState.split('.')[1];

                    var browserState = getOpBrowserState();

                    var sessionStateCalculated = sha256(clientId + ' ' + e.origin + ' ' + browserState + ' ' + salt) + '.' + salt;

                    if (sessionState == sessionStateCalculated) {
                        status = 'unchanged';
                    } else {
                        status = 'changed';
                    }
                } catch(err) {
                    status = 'error';
                }
                e.source.postMessage(status, e.origin);
            };

            function getOpBrowserState() {
                var theName = 'op_browser_state=';
                var theCookie = document.cookie + ';';
                var start = theCookie.indexOf(theName);
                if (start != -1)
                {
                    var end = theCookie.indexOf(';', start);
                    return unescape(theCookie.substring(start + theName.length, end));
                }
                throw new Error('We couldn\'t find the "op_browser_state" cookie.');
            }
        </script>
    </head>
    <body>
        OpenID Connect Session Management OP Iframe.
    </body>
</html>

oidc_provider/templates/oidc_provider/end_session_completed.html
<h1>End Session Completed</h1>

<p>You've been logged out.</p>

oidc_provider/templates/oidc_provider/end_session_failed.html
<h1>End Session Failed</h1>

<p>You can now close this window.</p>

oidc_provider/templates/oidc_provider/end_session_prompt.html
<h1>End Session</h1>

<p>Hi <strong>{{ user.email }}</strong>, are you sure you want to log out{% if client %} from <strong>{{ client.name }}</strong> app{% endif %}?</p>

<form method="post" action="{{ end_session_prompt_url }}">

    {% csrf_token %}

    <input type="submit" value="Cancel" />
    <input type="submit" name="allow" value="Yes" />

</form>

oidc_provider/templates/oidc_provider/error.html
<h3>{{ error }}</h3>
<p>{{ description }}</p>

oidc_provider/templates/oidc_provider/form_post.html
<html>
    <body onload="document.form.submit();">
        form post
        <form method="post" action="{{ redirect_url }}" name="form">
            {% csrf_token %}
            {% for field, value in params.items %}
                <input type="hidden" name="{{ field }}" value="{{ value }}" />
            {% endfor %}
        </form>

    </body>
</html>

oidc_provider/templates/oidc_provider/hidden_inputs.html
<input name="client_id" type="hidden" value="{{ params.client_id }}" />
<input name="redirect_uri" type="hidden" value="{{ params.redirect_uri }}" />
<input name="response_type" type="hidden" value="{{ params.response_type }}" />
<input name="scope" type="hidden" value="{{ params.scope | join:' ' }}" />
<input name="state" type="hidden" value="{{ params.state }}" />
{% if params.nonce %}<input name="nonce" type="hidden" value="{{ params.nonce }}" />{% endif %}
{% if params.code_challenge %}<input name="code_challenge" type="hidden" value="{{ params.code_challenge }}" />{% endif %}
{% if params.code_challenge_method %}<input name="code_challenge_method" type="hidden" value="{{ params.code_challenge_method }}" />{% endif %}

oidc_provider/templates/oidc_provider/logout_clients.html
{% for url in logout_urls %}
<iframe src="{{url|safe}}" data-oidc-logout height="0" width="0" style="visibility: hidden;display: none"></iframe>
{% endfor %}